name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'v0.1.0'
      upload_to_release:
        description: 'Upload to GitHub Release'
        required: false
        default: false
        type: boolean
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-pip \
          python3-setuptools
          
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('releases/v0.1.0/android/buildozer.spec') }}
        
    - name: Cache Buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('releases/v0.1.0/android/buildozer.spec') }}
        
    - name: Build APK
      working-directory: releases/v0.1.0/android
      run: |
        echo "Iniciando build de APK..."
        buildozer android debug
        echo "Build completado"

    - name: List generated files
      working-directory: releases/v0.1.0/android
      run: |
        echo "Archivos en bin/:"
        ls -la bin/ || echo "Directorio bin no encontrado"
        echo "Buscando APKs:"
        find . -name "*.apk" -type f || echo "No se encontraron APKs"

    - name: Rename APK
      working-directory: releases/v0.1.0/android
      run: |
        if [ -f bin/*.apk ]; then
          APK_FILE=$(ls bin/*.apk | head -1)
          cp "$APK_FILE" "bin/SiKIdle-${{ github.event.inputs.version || 'v0.1.0' }}-android.apk"
          echo "APK renombrado a: SiKIdle-${{ github.event.inputs.version || 'v0.1.0' }}-android.apk"
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SiKIdle-android-apk-${{ github.event.inputs.version || 'v0.1.0' }}
        path: releases/v0.1.0/android/bin/*.apk
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.upload_to_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: SiKIdle ${{ github.event.inputs.version || github.ref_name }}
        files: releases/v0.1.0/android/bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
